---
swagger: '2.0'
info:
  version: 1.0.0
  title: pets
paths:
  /:
    get:
      summary: Error!!!
      responses:
        '403':
          description: 'Success'
          schema:
            $ref: '#/definitions/ErrorModel'
    post:
      summary: Error!!!
      responses:
        '403':
          description: 'Success'
          schema:
            $ref: '#/definitions/ExtendedErrorModel'

definitions:

  ErrorModel:
    type: object
    required:
    - message
    - code
    properties:
      message:
        type: string
      code:
        type: integer
        minimum: 100
        maximum: 600

  ExtendedErrorModel:
    allOf:
    - $ref: '#/definitions/ErrorModel'
    - type: object
      required:
      - rootCause
      properties:
        rootCause:
          type: string
